<script type="text/javascript">
<!--
var tasoitusNro = <?php echo $tasoitusMaara; ?>;
function lisaaRivi() {
  $('#tasoitus').append('<tr><td><input type="text" name="tasoitus_' + tasoitusNro + '" /></td><td><input type="text" name="lahtien_' + tasoitusNro + '" value="<?php echo date("j.n.Y"); ?>" /></td></tr>');
  tasoitusNro++;
}
//-->
</script>

<?php
if ($lisaa) echo '<h3>Lisää pelaaja</h3>';
else echo '<h3>Muokkaa pelaajaa ' . $pelaajanTiedot['nimi'] . '</h3>';
?>
<form action="" method="post">
  <div>
    <b>Nimi:</b> <input type="text" name="nimi" value="<?php if (isset($pelaajanTiedot)) echo $pelaajanTiedot['nimi']; ?>" /><br /><br />
    <b>Sukupuoli:</b><br />
    <input type="radio" name="sukupuoli" value="nainen" <?php if (!isset($pelaajanTiedot) || $pelaajanTiedot['sukupuoli'] == 'nainen') echo 'checked="checked" '; ?>/> Nainen<br />
    <input type="radio" name="sukupuoli" value="mies" <?php if (isset($pelaajanTiedot) && $pelaajanTiedot['sukupuoli'] == 'mies') echo 'checked="checked" '; ?>/> Mies<br /><br />
    
    <b>Tasoitushistoria</b><br />
    (Päivämäärät muodossa d.m.yyyy)<br />
    <table class="table-simppeli" id="tasoitus">
      <tr>
        <td>Tasoitus</td>
        <td>Milloin tullut voimaan</td>
      </tr>
      <tr>
        <td>54</td>
        <td>-</td>
      </tr>
<?php
$i = 0;
foreach ($tasoitukset as $tasoitus) {
  echo '      <tr>
        <td><input type="text" name="tasoitus_' . $i . '" value="' . $tasoitus['tasoitus'] . '" /></td>
        <td><input type="text" name="lahtien_' . $i . '" value="' . $tasoitus['lahtien'] . '" /></td>
      </tr>
';
  $i++;
}
?>
    </table>
    <input type="button" value="Lisää tasoitus" onclick="lisaaRivi();" /><br /><br />
    <input type="submit" value="Tallenna" />
  </div>
</form>