<h3>Katso kierrosta</h3>
<table class="kahtiajako">
  <tr>
    <td>
      <b>Kenttä:</b> <?php echo $kentta['nimi']; ?><br />
      <b>Lähtöaika:</b> <?php echo date("j.n.Y G:i", $kierroksenTiedot['lahtoaika']); ?><br />
      <b>Tarkoitus:</b> <?php echo $kierroksenTiedot['tarkoitus']; ?><br />
      <b>Sää:</b> <?php echo $saat[$kierroksenTiedot['saa']]; ?><br />
      <b>Lämpötila:</b> <?php echo $kierroksenTiedot['lampotila']; ?>&deg;C<br />
      <b>Tuuli:</b> <?php echo $kierroksenTiedot['tuuli']; ?>m/s<br />
    </td>
    <td>
      <b>Muuta:</b><br />
      <?php echo $kierroksenTiedot['muuta']; ?>
    </td>
  </tr>
</table><br /><br />
<div id="scorecardit">
<?php 
foreach ($pelaajienTiedot as $pelaajaId => $pelaaja) {
  echo '<div id="pelaaja_' . $pelaajaId . '"><b>Pelaaja:</b> ' . $pelaaja['nimi'] . '<br />
<b>Tii:</b> ' . $pelaaja['tii'] . '<br />
<b>Tasoitus pelattaessa:</b> ' . $pelaaja['tasoitus'] . '<br />
<b>Slope pelattaessa:</b> ' . $pelaaja['slope'] . '<br />
<table class="table-simppeli">
  <tr>
    <td class="info">Väylä</td>
    <td class="info">Par</td>
    <td class="info">HCP</td>
    <td>Lyönnit</td>
    <td>Pisteet</td>
    <td>Aloituslyönti</td>
    <td>Greeniosuma</td>
    <td>Putit</td>
    <td>Bunkkeri</td>
    <td>Rankkarit</td>
  </tr>';
  foreach ($pelaaja['vaylat'] as $vaylanNumero => $vayla) {
    echo '  <tr>
    <td class="info">' . $vaylanNumero . '</td>
    <td class="info">' . $vayla['par'] . '</td>
    <td class="info">' . $vayla['hcp'] . '</td>
    <td>' . $vayla['lyonnit'] . '</td>
    <td>' . $vayla['pisteet'] . '</td>
    <td>' . $vayla['avaus'] . '</td>
    <td>' . (($vayla['greeniosuma'] == 'on')?'Kyllä':'Ei') . '</td>
    <td>' . $vayla['putit'] . '</td>
    <td>' . $bunkkerit[$vayla['bunkkerista']] . '</td>
    <td>' . $vayla['rankkari'] . '</td>
  </tr>
';
    if (($vaylanNumero == 9 || $vaylanNumero == 18) && $kentta['vaylia'] == 18) {
      $puolisko = ($vaylanNumero == 9)?'total_out':'total_in';
      echo '  <tr>
    <td class="info">' . (($vaylanNumero == 9)?'Out':'In') . '</td>
    <td class="info">' . $pelaaja[$puolisko]['par'] . '</td>
    <td class="info"></td>
    <td class="info">' . $pelaaja[$puolisko]['lyonnit'] . '</td>
    <td class="info">' . $pelaaja[$puolisko]['pisteet'] . '</td>
    <td class="info"></td>
    <td class="info">' . $pelaaja[$puolisko]['greeniosuma'] . '</td>
    <td class="info">' . $pelaaja[$puolisko]['putit'] . '</td>
    <td class="info">' . $pelaaja[$puolisko]['bunkkeri'] . '</td>
    <td class="info">' . $pelaaja[$puolisko]['rankkari'] . '</td>
  </tr>
        ';
    }
  }
  echo '  <tr>
    <td class="info">Total</td>
    <td class="info">' . $kentta['par'] . '</td>
    <td class="info"></td>
    <td class="info">' . $pelaaja['total']['lyonnit'] . '</td>
    <td class="info">' . $pelaaja['total']['pisteet'] . '</td>
    <td class="info"></td>
    <td class="info">' . $pelaaja['total']['greeniosuma'] . '</td>
    <td class="info">' . $pelaaja['total']['putit'] . '</td>
    <td class="info">' . $pelaaja['total']['bunkkeri'] . '</td>
    <td class="info">' . $pelaaja['total']['rankkari'] . '</td>
  </tr>
</table></div>';
}
?>
</div><br />
<a href="<?php echo Atomik::url('kierrokset/muokkaa', array('kierros' => $kierroksenTiedot['id'])); ?>">[Muokkaa]</a>
