<script type="text/javascript">
<!--
function toggleBunkkeri(pelaajaId, vayla) {
  $('select[name=pelaaja_' + pelaajaId + '_vayla_' + vayla + '_bunkkerista]').toggle();
}

pelaajienNimet = new Array();
pelaajienSukupuolet = new Array();
<?php
foreach ($pelaajat as $pelaajaId => $pelaaja) {
  echo '  pelaajienNimet[' . $pelaajaId . '] = \'' . $pelaaja['nimi'] . "';\r\n";
  echo '  pelaajienSukupuolet[' . $pelaajaId . '] = \'' . $pelaaja['sukupuoli'] . "';\r\n";
}
?>

function bindKeyup() {
  $('input[type=text]').keyup(function() {
    var focus = $('input:focus');
    if (focus.attr('name').substr(0, 8) == "pelaaja_" && focus.attr('value').length > 0) {
      var split = focus.attr('name').split('_');
      split[3]++;
      var seuraavaKentta = $('input[name=' + split.join('_') + ']');
      seuraavaKentta.focus();
      seuraavaKentta.select();
    }
  });
}

function lisaaPelaaja(pelaajanTiedot) {
  var pelaajaId;
  var tayta = false;
  if(pelaajanTiedot == null) {
    pelaajaId = $('#pelaajat').val();
    if(pelaajaId == null) return;
    $('#pelaajat option:selected').remove();
    pelaajanTiedot = new Array('');
    if(pelaajienSukupuolet[pelaajaId] == "mies") {
      pelaajanTiedot['tii'] = 'keltainen';
    } else {
      pelaajanTiedot['tii'] = 'punainen';
    }
  } else {
    pelaajaId = pelaajanTiedot['id'];
    tayta = true;
  }
  var lisattava = '<div id="pelaaja_' + pelaajaId + '"><b>Pelaaja:</b> ' + pelaajienNimet[pelaajaId] + '\
<div class="oikea"><a href="#" onclick="poistaPelaaja(' + pelaajaId + ')">Poista pelaaja</a></div><br />\
<b>Tii:</b> <table class="tiivalinta"><tr>';
  if(pelaajienSukupuolet[pelaajaId] == "mies") {
    lisattava += '<td class="v"><input type="radio" name="pelaaja_' + pelaajaId + '_tii" value="valkoinen" ' + ((pelaajanTiedot['tii'] == 'valkoinen') ? 'checked="checked" ' : '') + '/></td>';
  }
  lisattava += '<td class="k"><input type="radio" name="pelaaja_' + pelaajaId + '_tii" value="keltainen" ' + ((pelaajanTiedot['tii'] == 'keltainen') ? 'checked="checked" ' : '') + '/></td>\
<td class="s"><input type="radio" name="pelaaja_' + pelaajaId + '_tii" value="sininen" ' + ((pelaajanTiedot['tii'] == 'sininen') ? 'checked="checked" ' : '') + '/></td>\
<td class="p"><input type="radio" name="pelaaja_' + pelaajaId + '_tii" value="punainen" ' + ((pelaajanTiedot['tii'] == 'punainen') ? 'checked="checked" ' : '') + '/></td>\
</tr></table><br />\
<table class="table-simppeli">\
<tr>\
  <td class="info">Väylä</td>\
  <td class="info">Par</td>\
  <td class="info">HCP</td>\
  <td>Lyönnit</td>\
  <td>Aloituslyönti</td>\
  <td>Greeniosuma</td>\
  <td>Putit</td>\
  <td>Bunkkeri</td>\
  <td>Rankkarit</td>\
</tr>\
<?php 
foreach ($vaylaInfo as $vayla):
?><tr>\
  <td class="info"><?php echo $vayla['numero']; ?></td>\
  <td class="info"><?php echo $vayla['par']; ?></td>\
  <td class="info"><?php echo $vayla['hcp']; ?></td>\
  <td><input type="text" name="pelaaja_' + pelaajaId + '_vayla_<?php echo $vayla['numero']; ?>_lyonnit" size="2" ' + ((tayta) ? 'value="' + pelaajanTiedot['vaylat']['<?php echo $vayla['numero']; ?>']['lyonnit'] + '" ' : '') + '/></td>\
  <td><input type="radio" name="pelaaja_' + pelaajaId + '_vayla_<?php echo $vayla['numero']; ?>_avaus" value="vasen" ' + ((tayta && pelaajanTiedot['vaylat']['<?php echo $vayla['numero']; ?>']['avaus'] == 'vasen') ? 'checked="checked" ' : '') + '/>Vasen \
  <input type="radio" name="pelaaja_' + pelaajaId + '_vayla_<?php echo $vayla['numero']; ?>_avaus" value="vayla" ' + ((!tayta || pelaajanTiedot['vaylat']['<?php echo $vayla['numero']; ?>']['avaus'] == 'vayla') ? 'checked="checked" ' : '') + '/>Väylä \
  <input type="radio" name="pelaaja_' + pelaajaId + '_vayla_<?php echo $vayla['numero']; ?>_avaus" value="oikea" ' + ((tayta && pelaajanTiedot['vaylat']['<?php echo $vayla['numero']; ?>']['avaus'] == 'oikea') ? 'checked="checked" ' : '') + '/>Oikea</td>\
  <td><input type="checkbox" name="pelaaja_' + pelaajaId + '_vayla_<?php echo $vayla['numero']; ?>_greeniosuma" ' + ((tayta && pelaajanTiedot['vaylat']['<?php echo $vayla['numero']; ?>']['greeniosuma'] == 'on') ? 'checked="checked" ' : '') + '/></td>\
  <td><input type="text" name="pelaaja_' + pelaajaId + '_vayla_<?php echo $vayla['numero']; ?>_putit" size="2" ' + ((tayta) ? 'value="' + pelaajanTiedot['vaylat']['<?php echo $vayla['numero']; ?>']['putit'] + '" ' : '') + '/></td>\
  <td><input type="checkbox" name="pelaaja_' + pelaajaId + '_vayla_<?php echo $vayla['numero']; ?>_bunkkerissa" onclick="toggleBunkkeri(' + pelaajaId + ', <?php echo $vayla['numero']; ?>)" ' + ((tayta && pelaajanTiedot['vaylat']['<?php echo $vayla['numero']; ?>']['bunkkerissa'] == 'on') ? 'checked="checked" ' : '') + '/><select name="pelaaja_' + pelaajaId + '_vayla_<?php echo $vayla['numero']; ?>_bunkkerista"' + ((!tayta || pelaajanTiedot['vaylat']['<?php echo $vayla['numero']; ?>']['bunkkerissa'] != 'on') ? ' class="hidden"' : '') + '>\
    <option value="2">Miten onnistui?</option>\
    <option value="1"' + ((tayta && pelaajanTiedot['vaylat']['<?php echo $vayla['numero']; ?>']['bunkkerista'] == '1') ? ' selected="selected"' : '') + '>Hyvin</option>\
    <option value="2"' + ((tayta && pelaajanTiedot['vaylat']['<?php echo $vayla['numero']; ?>']['bunkkerista'] == '2' && pelaajanTiedot['vaylat']['<?php echo $vayla['numero']; ?>']['bunkkerissa'] == 'on') ? ' selected="selected"' : '') + '>Kohtalaisesti</option>\
    <option value="3"' + ((tayta && pelaajanTiedot['vaylat']['<?php echo $vayla['numero']; ?>']['bunkkerista'] == '3') ? ' selected="selected"' : '') + '>Huonosti</option>\
    </select></td>\
  <td><input type="text" name="pelaaja_' + pelaajaId + '_vayla_<?php echo $vayla['numero']; ?>_rankkari" size="2" ' + ((tayta) ? 'value="' + pelaajanTiedot['vaylat']['<?php echo $vayla['numero']; ?>']['rankkari'] + '" ' : '') + '/></td>\
</tr>\
<?php
endforeach;
?></table><br /></div>';
  $('#scorecardit').append(lisattava);
  bindKeyup();
}

function poistaPelaaja(pelaajaId) {
  $('#pelaaja_' + pelaajaId).remove();
  $('#pelaajat').append('<option value="' + pelaajaId + '">' + pelaajienNimet[pelaajaId] + "</option>\r\n");
}

$(document).ready(function() {
<?php
if (isset($pelaajienTiedot)) {
  echo "  var pelaajanTiedot;\r\n";
  foreach ($pelaajienTiedot as $pelaajaId => $pelaaja) {
    echo "  pelaajanTiedot = new Array();\r\n";
    echo "  pelaajanTiedot['id'] = '" . $pelaajaId . "';\r\n";
    $this->array_to_js($pelaaja, 'pelaajanTiedot', '  ');
    echo "  lisaaPelaaja(pelaajanTiedot);\r\n";
  }
}
?>
  bindKeyup();
});
//-->
</script>

<h3>Muokkaa kierrosta</h3>
<form action="" method="post">
  <div>
    <table class="kahtiajako">
      <tr>
        <td>
          <b>Kenttä:</b> <?php echo $kentta['nimi']; ?><br />
          <b>Lähtöaika:</b> <input type="text" name="lahtoaika" value="<?php echo (isset($kierroksenTiedot['lahtoaika']))? $kierroksenTiedot['lahtoaika'] : date("j.n.Y G:i"); ?>" /><br />
          <b>Tarkoitus:</b><br />
          <input type="radio" name="tarkoitus" value="harjoitus" <?php if (!isset($kierroksenTiedot['tarkoitus']) || $kierroksenTiedot['tarkoitus'] == 'harjoitus') echo 'checked="checked" '; ?>/> Harjoitus<br />
          <input type="radio" name="tarkoitus" value="kilpailu" <?php if (isset($kierroksenTiedot['tarkoitus']) && $kierroksenTiedot['tarkoitus'] == 'kilpailu') echo 'checked="checked" '; ?>/> Kilpailu<br />
          <b>Sää:</b> <select name="saa">
          <option value="0"<?php if (isset($kierroksenTiedot['saa']) && $kierroksenTiedot['saa'] == '0') echo ' selected="selected"'; ?>>Aurinkoinen</option>
          <option value="1"<?php if (isset($kierroksenTiedot['saa']) && $kierroksenTiedot['saa'] == '1') echo ' selected="selected"'; ?>>Pilvipouta</option>
          <option value="2"<?php if (isset($kierroksenTiedot['saa']) && $kierroksenTiedot['saa'] == '2') echo ' selected="selected"'; ?>>Sadekuuroja</option>
          <option value="3"<?php if (isset($kierroksenTiedot['saa']) && $kierroksenTiedot['saa'] == '3') echo ' selected="selected"'; ?>>Jatkuva sade</option>
          </select><br />
          <b>Lämpötila:</b> <input type="text" name="lampotila" <?php if (isset($kierroksenTiedot['lampotila'])) echo ' value="' . $kierroksenTiedot['lampotila'] . '" '; ?>/>&deg;C<br />
          <b>Tuuli:</b> <input type="text" name="tuuli" <?php if (isset($kierroksenTiedot['tuuli'])) echo ' value="' . $kierroksenTiedot['tuuli'] . '" '; ?>/>m/s<br />
        </td>
        <td>
          <b>Muuta:</b><br />
          <textarea name="muuta" rows="5" cols="40"><?php if (isset($kierroksenTiedot['muuta'])) echo $kierroksenTiedot['muuta']; ?></textarea>
        </td>
      </tr>
    </table><br /><br />
    <select id="pelaajat">
<?php 
foreach ($pelaajat as $pelaajaId => $pelaaja) {
  if (!isset($pelaajienTiedot[$pelaajaId])) echo '<option value="' . $pelaajaId . '">' . $pelaaja['nimi'] . "</option>\r\n";
}
?>
    </select>
    <input type="button" value="Lisää pelaaja" onclick="lisaaPelaaja(null)" /><br /><br />
    <div id="scorecardit"></div>
    
    <br /><input type="submit" value="Lähetä" />
  </div>
</form>
