<b>Lisää kenttä:</b><br />
<form action="" method="post">
  Nimi: <input type="text" name="nimi" /><br />
  CR ja Slope (muodossa CR/Slope):<br />
  <table class="crslope">
    <tr>
      <td></td>
      <td>Miehet</td>
      <td>Naiset</td>
    </tr>
    <tr>
      <td style="background-color: white;"></td>
      <td><input type="text" name="crslopemv" /></td>
      <td></td>
    </tr>
    <tr>
      <td style="background-color: yellow;"></td>
      <td><input type="text" name="crslopemk" /></td>
      <td><input type="text" name="crslopenk" /></td>
    </tr>
    <tr>
      <td style="background-color: blue;"></td>
      <td><input type="text" name="crslopems" /></td>
      <td><input type="text" name="crslopens" /></td>
    </tr>
    <tr>
      <td style="background-color: red;"></td>
      <td><input type="text" name="crslopemp" /></td>
      <td><input type="text" name="crslopenp" /></td>
    </tr>
  </table><br />
  <input type="submit" value="Lähetä" />
</form>