<div class="center">
  <img src="<?php echo Atomik::url('/stats/image', array('pelaaja' => $pelaaja['id'], 'graafi' => 1)); ?>" alt="Tasoitus" /><br /><br />
  <img src="<?php echo Atomik::url('/stats/image', array('pelaaja' => $pelaaja['id'], 'graafi' => 2)); ?>" alt="Kierroksia viimeisen 5 viikon aikana" /><br /><br />
  <img src="<?php echo Atomik::url('/stats/image', array('pelaaja' => $pelaaja['id'], 'graafi' => 3)); ?>" alt="Bogeypisteitä kierroksittain" /><br /><br />
  <img src="<?php echo Atomik::url('/stats/image', array('pelaaja' => $pelaaja['id'], 'graafi' => 4)); ?>" alt="Putit kierroksittain" />
</div>